# **Numpy Matricies**

In [30]:
import numpy as np
import numpy.linalg

In [31]:
v1=np.matrix([[1,3,5,7],[2,4,6,8]])
print(v1)
print()
print(type(v1))

[[1 3 5 7]
 [2 4 6 8]]

<class 'numpy.matrix'>


In [32]:
v2=np.matrix([[9,8,7,6],[5,4,3,2]])
print(v2)
print()
print(type(v2))

[[9 8 7 6]
 [5 4 3 2]]

<class 'numpy.matrix'>


Addition of matricies

In [33]:
#Addition
print(v1+v2)

[[10 11 12 13]
 [ 7  8  9 10]]


Multiplication of matricies

In [34]:
v3=np.matrix([[1,3,5,7],[2,4,6,8]])
v4=np.matrix([[1,2],[3,4],[5,6],[7,8]])
print(v3)
print()
print(v4)


[[1 3 5 7]
 [2 4 6 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
print(v3*v4)
print()
print(v3.dot(v4))

[[ 84 100]
 [100 120]]

[[ 84 100]
 [100 120]]


In [56]:
print(np.matmul(v3,v4))

[[ 84 100]
 [100 120]]


Transpose

In [36]:
print(np.transpose(v4))

[[1 3 5 7]
 [2 4 6 8]]


In [37]:
print(np.matrix_transpose(v4))

[[1 3 5 7]
 [2 4 6 8]]


In [40]:
print(v4.T)

[[1 3 5 7]
 [2 4 6 8]]


In [41]:
print(np.swapaxes(v4,0,1))

[[1 3 5 7]
 [2 4 6 8]]


Inverse

In [45]:
v5=np.matrix([[1,2],[3,4]])
print(np.linalg.inv(v5))

[[-2.   1. ]
 [ 1.5 -0.5]]


Power

In [49]:
v5

matrix([[1, 2],
        [3, 4]])

In [50]:
print(np.linalg.matrix_power(v5,4))

[[199 290]
 [435 634]]


Determinate

In [54]:
v5

matrix([[1, 2],
        [3, 4]])

In [55]:
print(np.linalg.det(v5))

-2.0000000000000004


**Eigen values and Eigen vectors**

In [57]:
v5

matrix([[1, 2],
        [3, 4]])

In [58]:
print(np.linalg.eig(v5))

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=matrix([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))
