# Numpy Basics

In [1]:
import numpy as np

**Types of Creation of arrays**

In [2]:
a=np.array([1,2,3,4,5]) #1 dimensional
print(a)

[1 2 3 4 5]


In [3]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [4]:
a2=np.array([1,2,3],ndmin=10)
print(a2)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [5]:
print(a1.ndim)

2


In [6]:
a3=np.ones((5,5))
print(a3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
a4=np.zeros((10,5))
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
a5=np.eye(3)
print(a5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a6=np.linspace(1,10,num=5)
print(a6)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
a7=np.arange(1,20,2).reshape((5,2))
print(a7)
print()
print(a7.ndim)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]

2


**Data Types in Numpy Arrays**

In [11]:
b=np.array([1,2,3,4,5,6],ndmin=2 ,dtype='U') #You can replace U with int,float,string,complex,boolean,object,,etc..
print(b)
print()
print(b.dtype)


[['1' '2' '3' '4' '5' '6']]

<U1


In [12]:
# We can use astype() as well for the Conversion of the data type
#For example,
b1=a.astype(float)
print(b1)
print()
print(a)

[1. 2. 3. 4. 5.]

[1 2 3 4 5]


In [13]:
b1=b1.astype(complex)
print(b1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


**Shaping and Reshaping of Arrays**

In [14]:
#Shape
c=np.array([1,2,3,4,5,6])
print(c)
print()
print(c.shape)

[1 2 3 4 5 6]

(6,)


In [15]:
c.shape=(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [16]:
c.shape=(6,)
print(c)

[1 2 3 4 5 6]


In [17]:
c=c.reshape((3,2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
c=c.reshape(-1) #When we give '-1' as the attribute in reshape function Then it returns 1D Array
print(c)

[1 2 3 4 5 6]


**Arthemetic operations**

In [19]:
d=np.array([[1,2,3],[4,5,6]])
print(d)
print()
e=np.array([[1,2,3],[4,5,6]])
print(e)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


Addition

In [20]:
print(d+e) #using + operator
print()
print(np.add(d,e)) #using Numpy's Function

[[ 2  4  6]
 [ 8 10 12]]

[[ 2  4  6]
 [ 8 10 12]]


Subctration

In [21]:
print(d-e)
print()
print(np.subtract(d,e))

[[0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]]


Multiply

In [22]:
print(d*e)
print()
print(np.multiply(d,e))

[[ 1  4  9]
 [16 25 36]]

[[ 1  4  9]
 [16 25 36]]


Division

In [23]:
print(d/e)
print()
print(np.divide(d,e))

[[1. 1. 1.]
 [1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]]


power

In [24]:
print(d**e)
print()
print(np.pow(d,e))

[[    1     4    27]
 [  256  3125 46656]]

[[    1     4    27]
 [  256  3125 46656]]


Modulus

In [25]:
print(d%e)
print()
print(np.mod(d,e))

[[0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]]


Reciprocal

In [26]:
print(1/d)
print()
print(np.reciprocal(d))

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[1 0 0]
 [0 0 0]]


Some More::
    min 
    max
    argmin
    argmax
    sqrt
    sin
    cos
    cumsum

In [27]:
print(np.min(d))

1


In [28]:
print(np.max(d))

6


In [29]:
print(np.argmin(d))

0


In [30]:
print(np.argmax(d))

5


In [31]:
print(np.sqrt(d))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [32]:
print(np.sin(d))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


In [33]:
print(np.cos(d))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


In [34]:
print(np.cumsum(d))

[ 1  3  6 10 15 21]


In [38]:
print(a)
print()
print(np.mean(a))

[1 2 3 4 5]

3.0


In [39]:
print(np.std(a))

1.4142135623730951
