# Indexing and slicing of Numpy arrays

In [2]:
import numpy as np

In [3]:
#1 d Array slicing
a= np.array([1,2,3,4,5,6,7,8,9])
print(a[5])
print()
print(a[1:7:2])

6

[2 4 6]


In [4]:
#2 D arrays
b1=np.array([[1,2,3],[4,5,6]])
print(b1)
print()
print(a[5])

[[1 2 3]
 [4 5 6]]

6


In [5]:
print(b1[1,2])

6


In [6]:
b1[1,:2]

array([4, 5])

# Iterating Numpy Arrays

In [7]:
for i in a:
    print(i)


1
2
3
4
5
6
7
8
9


In [8]:
for i in b1:
    for j in i:
        print(j)

1
2
3
4
5
6


In [9]:
for i in np.nditer(a):

    print(i)

1
2
3
4
5
6
7
8
9


In [10]:
for i in np.nditer(b1):
    print(i)

1
2
3
4
5
6


In [11]:
for i,d in np.ndenumerate(a):
    print(i,d)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 7
(7,) 8
(8,) 9


In [12]:
for i,d in np.ndenumerate(b1):
    print(i,d)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


# Copy Vs View

In [13]:
var1=np.array([6,5,4,3,2,1])
var2=np.array([9,8,7,6,5,4])


In [14]:
print("Copy")
c1=var1.copy()
print(c1)
c1[1]=7
print()
print("Copied and modified array:",c1)
print("orginal array",var1)
var1[-1]=0
print()
print("orginal Modified Array:",var1)
print("Copied array:",c1)

Copy
[6 5 4 3 2 1]

Copied and modified array: [6 7 4 3 2 1]
orginal array [6 5 4 3 2 1]

orginal Modified Array: [6 5 4 3 2 0]
Copied array: [6 7 4 3 2 1]


In [15]:
print("view")
v1=var2.view()
print(v1)
v1[-1]=3
print()
print("Viewed and Modified Array:",v1)
print("Orginal array:",var2)
print()
var2[0]=0
print("orginal Modified Array:",var2)
print("Viewed Array:",v1)

view
[9 8 7 6 5 4]

Viewed and Modified Array: [9 8 7 6 5 3]
Orginal array: [9 8 7 6 5 3]

orginal Modified Array: [0 8 7 6 5 3]
Viewed Array: [0 8 7 6 5 3]


# Joining of arrays

In [16]:
com_arr=np.concatenate((var1,var2))
print("Combined Array::",com_arr)

Combined Array:: [6 5 4 3 2 0 0 8 7 6 5 3]


In [17]:
ar1=np.stack((var1,var2))
print(ar1)

[[6 5 4 3 2 0]
 [0 8 7 6 5 3]]


In [18]:
var3=np.array([[1,2,3,4],[5,6,7,8]])
print(var3)
print()
var4=np.array([[9,8,7,6],[5,4,3,2]])
print(var4)

[[1 2 3 4]
 [5 6 7 8]]

[[9 8 7 6]
 [5 4 3 2]]


In [19]:
np.concatenate((var3,var4),axis=1)

array([[1, 2, 3, 4, 9, 8, 7, 6],
       [5, 6, 7, 8, 5, 4, 3, 2]])

In [20]:
ar2=np.stack((var3,var4),axis=1)
print(ar2)

[[[1 2 3 4]
  [9 8 7 6]]

 [[5 6 7 8]
  [5 4 3 2]]]


In [21]:
ar2=np.hstack((var3,var4))
print(ar2)

[[1 2 3 4 9 8 7 6]
 [5 6 7 8 5 4 3 2]]


In [22]:
ar2=np.vstack((var3,var4))
print(ar2)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]
 [5 4 3 2]]


In [23]:
ar2=np.dstack((var3,var4))
print(ar2)

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]

 [[5 5]
  [6 4]
  [7 3]
  [8 2]]]


# Split

In [24]:
var4

array([[9, 8, 7, 6],
       [5, 4, 3, 2]])

In [25]:
var5=np.split(var4,2)
print(var5)

[array([[9, 8, 7, 6]]), array([[5, 4, 3, 2]])]


In [26]:
var1

array([6, 5, 4, 3, 2, 0])

In [27]:
np.split(var1,6)

[array([6]), array([5]), array([4]), array([3]), array([2]), array([0])]

In [28]:
np.split(var4,4,axis=1)

[array([[9],
        [5]]),
 array([[8],
        [4]]),
 array([[7],
        [3]]),
 array([[6],
        [2]])]

# Search 

Unsorted array  :: where()

In [29]:
v2=np.array([1,2,3,4,5,6,2,5,6,7,2,5,8,9,7])
x=np.where(v2==2)
print(x)


(array([ 1,  6, 10]),)


In [30]:
np.where((v2%2)==0)

(array([ 1,  3,  5,  6,  8, 10, 12]),)

Sorted Array :: searchsorted()

In [31]:
v3=np.array([1,2,3,5,6,7,8,9,11])
x1=np.searchsorted(v3,4)
print(x1)

3


In [32]:
np.searchsorted(v3,[5,6,7,8])

array([3, 4, 5, 6])

# Sorting 

In [33]:
v2

array([1, 2, 3, 4, 5, 6, 2, 5, 6, 7, 2, 5, 8, 9, 7])

In [34]:
np.sort(v2)

array([1, 2, 2, 2, 3, 4, 5, 5, 5, 6, 6, 7, 7, 8, 9])

# Filter 

In [35]:
v4=np.array(['a','b','d','s','h'])
t1=[True,False,True,True,False]
fil=v4[t1]
print(fil)

['a' 'd' 's']


# Arthemetic Functions

Shuffle

In [36]:

v3

array([ 1,  2,  3,  5,  6,  7,  8,  9, 11])

In [37]:
np.random.shuffle(v3)
print(v3)

[11  8  9  5  2  6  1  3  7]


Unique

In [38]:
v2

array([1, 2, 3, 4, 5, 6, 2, 5, 6, 7, 2, 5, 8, 9, 7])

In [39]:
np.unique(v2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Resize

In [40]:
v5=np.array([1,2,3,4,5,6,7,8])
v5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
r=np.resize(v5,(2,4))
print(r)

[[1 2 3 4]
 [5 6 7 8]]


flatten

In [42]:
r

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
r.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

Ravel

In [44]:
r

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
r1=np.ravel(r)
print(r1)

[1 2 3 4 5 6 7 8]


# Insert & Delete 

insert()

In [46]:
v6=np.array([1,2,3,4,5,6,7,8])
print(v6)
print()
v7=np.insert(v6,0,0)
print(v7)


[1 2 3 4 5 6 7 8]

[0 1 2 3 4 5 6 7 8]


In [47]:
print(v6)

[1 2 3 4 5 6 7 8]


In [48]:
v8=np.array([[1,2,3,4],[9,8,7,6]])
print(v8)
print()
v9=np.insert(v8,2,30,axis=0)
print(v9)

[[1 2 3 4]
 [9 8 7 6]]

[[ 1  2  3  4]
 [ 9  8  7  6]
 [30 30 30 30]]


append()

In [49]:
ap=np.array([1,2,3,4])
print(ap)
print()
ap1=np.append(ap,(7,8,9))

print(ap1)

[1 2 3 4]

[1 2 3 4 7 8 9]


Delete

In [50]:
ap

array([1, 2, 3, 4])

In [51]:
d1=np.delete(ap,3)
print(d1)

[1 2 3]


# Handling missing Data in Arrays

In [60]:
a=np.array([1,2,3,np.nan,4,5,6,np.inf,-np.inf])
a

array([  1.,   2.,   3.,  nan,   4.,   5.,   6.,  inf, -inf])

1. Identify the nan values :: np.isnan()

In [56]:
nan_musk=np.isnan(a)
print(nan_musk)

[False False False  True False False False  True]


2. Replacinng nan to num :: np.nan_to_num()

In [65]:
ar_replaced=np.nan_to_num(a,nan=0,posinf=100,neginf=-100)
print(ar_replaced)

[   1.    2.    3.    0.    4.    5.    6.  100. -100.]
