# Numpy Basics

In [30]:
import numpy as np

**Types of Creation of arrays**

In [60]:
a=np.array([1,2,3,4,5]) #1 dimensional
print(a)

[1 2 3 4 5]


In [61]:
a1=np.array([[1,2,3],[4,5,6]])
print(a1)

[[1 2 3]
 [4 5 6]]


In [62]:
a2=np.array([1,2,3],ndmin=10)
print(a2)

[[[[[[[[[[1 2 3]]]]]]]]]]


In [63]:
print(a1.ndim)

2


In [64]:
a3=np.ones((5,5))
print(a3)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [65]:
a4=np.zeros((10,5))
print(a4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [66]:
a5=np.eye(3)
print(a5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [67]:
a6=np.linspace(1,10,num=5)
print(a6)

[ 1.    3.25  5.5   7.75 10.  ]


In [68]:
a7=np.arange(1,20,2).reshape((5,2))
print(a7)
print()
print(a7.ndim)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]

2


**Data Types in Numpy Arrays**

In [69]:
b=np.array([1,2,3,4,5,6],ndmin=2 ,dtype='U') #You can replace U with int,float,string,complex,boolean,object,,etc..
print(b)
print()
print(b.dtype)


[['1' '2' '3' '4' '5' '6']]

<U1


In [70]:
# We can use astype() as well for the Conversion of the data type
#For example,
b1=a.astype(float)
print(b1)
print()
print(a)

[1. 2. 3. 4. 5.]

[1 2 3 4 5]


In [71]:
b1=b1.astype(complex)
print(b1)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


**Shaping and Reshaping of Arrays**

In [72]:
#Shape
c=np.array([1,2,3,4,5,6])
print(c)
print()
print(c.shape)

[1 2 3 4 5 6]

(6,)


In [73]:
c.shape=(2,3)
print(c)

[[1 2 3]
 [4 5 6]]


In [74]:
c.shape=(6,)
print(c)

[1 2 3 4 5 6]


In [77]:
c=c.reshape((3,2))
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [81]:
c=c.reshape(-1) #When we give '-1' as the attribute in reshape function Then it returns 1D Array
print(c)

[1 2 3 4 5 6]


**Arthemetic operations**